name: on-pullrequest

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.re'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  invoke-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get AWS OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ vars.AWS_ROLE }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
             **.re

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Run run.sh
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          AWS_BEDROCK_MODEL_ID: ${{ vars.AWS_BEDROCK_MODEL_ID }}
          AWS_BEDROCK_REGION: ${{ vars.AWS_BEDROCK_REGION }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            bash .github/script/run.sh .github/prompt/system.txt ${file}
            response_body=`cat outfile.json | jq -r -c '.content[-1].text'`
            gh pr comment "${PR_NUMBER}" -b "${response_body}"
          done
